// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYf6k-vBrRwIbObXSC8B_ZmH6bTfCH4J4',
    appId: '1:90661597107:web:fc03ed7de48b4af79825c6',
    messagingSenderId: '90661597107',
    projectId: 'adminschoolbus',
    authDomain: 'adminschoolbus.firebaseapp.com',
    storageBucket: 'adminschoolbus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyuJPF9ta7Ics-ihdPlosi7e6ilQuoCWo',
    appId: '1:90661597107:android:81a8271e70ebb1739825c6',
    messagingSenderId: '90661597107',
    projectId: 'adminschoolbus',
    storageBucket: 'adminschoolbus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF_dlwqfv9KkPWN3xvoPkU-0kM88ugezU',
    appId: '1:90661597107:ios:77e5e4a80fc06d0e9825c6',
    messagingSenderId: '90661597107',
    projectId: 'adminschoolbus',
    storageBucket: 'adminschoolbus.appspot.com',
    iosClientId: '90661597107-genvs8ilq2nb33ri6t03nbptajg94bf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolBusTrackingManagementSystemAdminModule',
  );
}
